version: "3"

services:
    app:
        build:
            context: .
            args:
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
        volumes:
            - ./:/src
        ports:
            - 8503:8503
        networks:
            - zmodules

networks:
  zmodules:
    driver: bridge
