version: "3.5"

services:
    app:
        build:
            context: .
            args:
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
            dockerfile: docker/Dockerfile
        volumes:
            - ./:/src
        ports:
            - 8503:8503
        depends_on:
            -   metadata_db
        networks:
            zmodules:
                aliases:
                    - metadata

    metadata_db:
        image: postgres:14
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5403:5432
        networks:
            - zmodules

    graphite:
        image: graphiteapp/graphite-statsd
        ports:
            - 8010:80
            - 2003:2003
            - 2004:2004
            - 2023:2023
            - 2024:2024
            - 8125:8125/udp
            - 8126:8126
        networks:
            - zmodules

networks:
  zmodules:
    driver: bridge
    name: zmodules
